feat(CI): make job skippable for non-py changes
apparently I had been working on something like this in April 2025!
implement skip-changelog label
one job status to check
include summary messages of why failed

As a result of incorporating the changelog check, this should no longer
run on commits to `develop`, which shouldn't be a problem as we don't
directly push there anymore anyways.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,14 +1,32 @@
-name: Test
+name: Validation
 on:
   pull_request:
-  push:
-    branches: [master, develop]
-  workflow_dispatch:
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
   cancel-in-progress: true
 jobs:
+  check-paths:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: dorny/paths-filter@v4
+        id: filter
+        with:
+          filters: |
+            nondoc:
+              - '!**/*.rst'
+            hasLog:
+              - added: 'changes/*'
+            py:
+              - '*.py'
+    outputs:
+      shouldTest: ${{ steps.filter.outputs.nondoc == 'true' }}
+      needsLog: ${{ steps.filter.outputs.py == 'true' }}
+      changelogged: ${{ steps.filter.outputs.hasLog == 'true' }}
+
   build-test:
+    name: Continuous Integration
+    needs: check-paths
+    if: needs.check-paths.outputs.shouldTest
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
@@ -20,8 +38,6 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v7
-        with:
-          fetch-depth: 0
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v6
         with:
@@ -34,3 +50,30 @@ jobs:
           pip install --editable ".[dev]"
       - name: Test with tox
         run: tox -e py
+
+  changelog:
+    name: Changelog requirement
+    needs: check-paths
+    if: |
+      needs.check-paths.outputs.needsLog &&
+      !contains(github.event.pull_request.labels.*.name, 'skip-changelog') &&
+      !contains(github.event.pull_request.labels.*.name, 'dependencies') &&
+      github.event.pull_request.user.name != 'pre-commit-ci'
+    # impossible to make pre-commit-ci add label "at least not for free tier"
+    runs-on: ubuntu-latest
+    steps:
+      - run: |
+          exit $([[ ${{ needs.check-paths.outputs.changelogged }} == 'true' ]])
+
+  pass:
+    name: Summary
+    needs: [ build-test, changelog ]
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail if changelog ran and failed
+        if: ${{ needs.changelog.result == 'failure' }}
+        run: echo "Please follow instructions under https://github.com/cpplint/cpplint/blob/crytown/CONTRIBUTING.rst#pull-requests to add a changelog entry\nor request the 'skip-changelog' label if you believe the changes should not be in the changelog."; exit 1
+      - name: Fail if build-test ran and failed
+        if: ${{ needs.build-test.result == 'failure' }}
+        run: echo "Failed required test(s).\nSee https://github.com/cpplint/cpplint/blob/develop/CONTRIBUTING.rst#testing for help on testing."; exit 1
